
server:
  port: 8888
  
spring:
  cloud:
    config:
      server:
        git:
          default-label: main
          uri: https://github.com/RodrigoFranco91/microservice-repo-alura
          search-paths: fornecedor
